#ifndef ENDPOINTLIST_H
#define ENDPOINTLIST_H
#ifndef UTEST

#define THE_DOMAIN 1
#define RED_NODE 14
#define RED_SCL_OUT 1
#define YELLOW_NODE 13
#define YELLOW_SCL_IN 1

#define YELLOW_MSG {1, 13, 0}
#define RED_MSG {1, 14, 0}
#define BLUE_MSG {1, 15, 0}
#define GREEN_MSG {1, 12, 0}

#define YELLOW_SIN {1, 13, 1}
#define YELLOW_COS {1, 13, 2}
#define RED_SIN {1, 14, 1}
#define BLUE_COS {1, 15, 1}
#define YELLOW_PKT {1, 13, 3}
#define GREEN_PKT {1, 12, 1}

#define MAG_CYAN_SEND {1, 10, 0}
#define MAG_CYAN_RECV {1, 11, 0}
#define CYAN_MAG_SEND {1, 11, 1}
#define CYAN_MAG_RECV {1, 10, 1}

#define FLIMSY {1, 9, 0}
#define STURDY {1, 8, 0}

#define YELLOW_MSG_DEF { YELLOW_MSG, MCAPI_NO_CHAN, CHAN_NO_DIR }
#define RED_MSG_DEF { RED_MSG, MCAPI_NO_CHAN, CHAN_NO_DIR, }
#define BLUE_MSG_DEF { BLUE_MSG, MCAPI_NO_CHAN, CHAN_NO_DIR }
#define GREEN_MSG_DEF { GREEN_MSG, MCAPI_NO_CHAN, CHAN_NO_DIR, }

#define YELLOW_SIN_DEF { YELLOW_SIN, MCAPI_SCL_CHAN, CHAN_DIR_RECV, RED_SIN, 2 }
#define YELLOW_COS_DEF { YELLOW_COS, MCAPI_SCL_CHAN, CHAN_DIR_RECV, BLUE_COS, 2 }
#define RED_SIN_DEF { RED_SIN, MCAPI_SCL_CHAN, CHAN_DIR_SEND, YELLOW_SIN, 2 }
#define BLUE_COS_DEF { BLUE_COS, MCAPI_SCL_CHAN, CHAN_DIR_SEND, YELLOW_COS, 2 }
#define YELLOW_PKT_DEF { YELLOW_PKT, MCAPI_PKT_CHAN, CHAN_DIR_SEND, GREEN_PKT, 0 }
#define GREEN_PKT_DEF { GREEN_PKT, MCAPI_PKT_CHAN, CHAN_DIR_RECV, YELLOW_PKT, 0 }

#define MAG_CYAN_SEND_DEF { MAG_CYAN_SEND, MCAPI_PKT_CHAN, CHAN_DIR_SEND, MAG_CYAN_RECV, 0 }
#define MAG_CYAN_RECV_DEF { MAG_CYAN_RECV, MCAPI_PKT_CHAN, CHAN_DIR_RECV, MAG_CYAN_SEND, 0 }
#define CYAN_MAG_SEND_DEF { CYAN_MAG_SEND, MCAPI_PKT_CHAN, CHAN_DIR_SEND, CYAN_MAG_RECV, 0 }
#define CYAN_MAG_RECV_DEF { CYAN_MAG_RECV, MCAPI_PKT_CHAN, CHAN_DIR_RECV, CYAN_MAG_SEND, 0 }

#define FLIMSY_DEF { FLIMSY, MCAPI_PKT_CHAN, CHAN_DIR_SEND, STURDY, 0 }
#define STURDY_DEF { STURDY, MCAPI_PKT_CHAN, CHAN_DIR_RECV, FLIMSY, 0 }

#define DEF_LIST { YELLOW_MSG_DEF, RED_MSG_DEF, BLUE_MSG_DEF, GREEN_MSG_DEF, \
YELLOW_SIN_DEF, YELLOW_COS_DEF, RED_SIN_DEF, BLUE_COS_DEF, YELLOW_PKT_DEF, GREEN_PKT_DEF, MAG_CYAN_SEND_DEF, MAG_CYAN_RECV_DEF, CYAN_MAG_SEND_DEF, CYAN_MAG_RECV_DEF, FLIMSY_DEF, STURDY_DEF }

#endif
#endif
